kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

metadata:
  namespace: default

steps:
# - name: Test the repository
#   image: node  
#   commands:
#   - npm install
#   - npm test

- name: Build and Push the repository
  image: plugins/docker
  settings:
    username: 
      from_secret: docker-user
    password: 
      from_secret: docker-pass
    repo: tpleugenerebong/deploy-test
    tags: development
- name: Deploy the image
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl delete -f ./k8s/development
    - kubectl create -f ./k8s/development
  
trigger:
  branch:
    include:
    - master
    - develop
    - feature/*