kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

metadata:
  namespace: default

steps:
# - name: tester
#   image: node  
#   commands:
#   - npm install
#   - npm test
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_user
    password: 
      from_secret: docker_pass
    repo: tpleugenerebong/deploy-test
  # - docker build -t tpleugenerebong/deploy-test:develop .
  # - docker push tpleugenerebong/deploy-test:develop

trigger:
  branch:
    include:
    - master
    - develop
    - feature/*