kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

metadata:
  namespace: default

steps:
- name: frontend
  image: node
  commands:
  - npm install
  - npm test
  - docker build -t tpleugenerebong/deploy-test:develop
  when:
    branch:
      include:
        - feature/*
steps:
- name: frontend
  image: node
  commands:
  - npm install
  - npm test
  - docker build -t tpleugenerebong/deploy-test:master
  when:
    branch:
      include:
        - master

trigger:
  branch:
    include:
    - master
    - develop
    - feature/*