kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

metadata:
  namespace: default

steps:
- name: tester
  image: node  
  volumes:
    - name: cache
      path: /.
  commands:
  - npm install
  - npm test
- name: docker
  image: docker  
  volumes:
    - name: cache
      path: /.
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  commands:
  - ls
  - docker build -t tpleugenerebong/deploy-test:develop .
  - docker push tpleugenerebong/deploy-test:develop

trigger:
  branch:
    include:
    - master
    - develop
    - feature/*