kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

metadata:
  namespace: default

steps:
- name: Test the repository
  image: node  
  commands:
  - npm install
  - npm test
- name: Build and Push the repository
  image: plugins/docker
  settings:
    username: 
      from_secret: docker-user
    password: 
      from_secret: docker-pass
    repo: tpleugenerebong/deploy-test
    tags: latest
  # - docker build -t tpleugenerebong/deploy-test:develop .
  # - docker push tpleugenerebong/deploy-test:develop

trigger:
  branch:
    include:
    - master
    - develop
    - feature/*